variables:
  PROJECT_NAME: TestFirebaseAll

stages:  
  - build
  - deploy

build-arm64:
  stage: build
  image: rabits/qt:5.15-android
  artifacts:
    name: aab-arm64
    paths:
      - ./dist/build/outputs/
    expire_in: 1 week
  script:
    - export
    - mkdir build
    - cd build
    - qmake ../${PROJECT_NAME}.pro -spec android-clang "CONFIG+=qtquickcompiler" ANDROID_ABIS="arm64-v8a"
    - make
    - make INSTALL_ROOT=../dist install
    - cd .. 
    - sudo chown -R $(whoami) $ANDROID_HOME
    - androiddeployqt --input ./build/android-${PROJECT_NAME}-deployment-settings.json --output ./dist --aab --deployment bundled --gradle --release

deploy:
  stage: deploy
  image: zl0i/firebase-cli:latest
  before_script:
    - export FIREBASE_TOKEN=${FIREBASE_TOKEN}
  script:
    - export
    - firebase projects:list 